// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcDkYjaNKR3nTvIVpPc6UuYfOEoqi7NKk',
    appId: '1:1004839329033:web:39b112a17c70860f0707d8',
    messagingSenderId: '1004839329033',
    projectId: 'hatti-49439',
    authDomain: 'hatti-49439.firebaseapp.com',
    storageBucket: 'hatti-49439.appspot.com',
    measurementId: 'G-EMGCSE7WS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0sVEIBOhHYyPq5qoX1AntN49lxaOVtrk',
    appId: '1:1004839329033:android:260ce7cdd594449e0707d8',
    messagingSenderId: '1004839329033',
    projectId: 'hatti-49439',
    storageBucket: 'hatti-49439.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu8RR2iB8ODRSvyrdkR1Qgr5u_9W1fkLg',
    appId: '1:1004839329033:ios:6fd5c6a13bfd07da0707d8',
    messagingSenderId: '1004839329033',
    projectId: 'hatti-49439',
    storageBucket: 'hatti-49439.appspot.com',
    androidClientId: '1004839329033-h91f05vp6il4nlpdlg1ggvkas38f273r.apps.googleusercontent.com',
    iosClientId: '1004839329033-1e9frtn06k01s99d2qvda4v082sb0tat.apps.googleusercontent.com',
    iosBundleId: 'com.Abhinav.ecart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu8RR2iB8ODRSvyrdkR1Qgr5u_9W1fkLg',
    appId: '1:1004839329033:ios:2ec32ff3d987f4d70707d8',
    messagingSenderId: '1004839329033',
    projectId: 'hatti-49439',
    storageBucket: 'hatti-49439.appspot.com',
    androidClientId: '1004839329033-h91f05vp6il4nlpdlg1ggvkas38f273r.apps.googleusercontent.com',
    iosClientId: '1004839329033-7mqes0r08l3buvdacpbgkoke348cnse7.apps.googleusercontent.com',
    iosBundleId: 'com.Abhinav.ecart.RunnerTests',
  );
}
